Json support
CIA-hideout/pongstar pull request #2
Opened 2017-01-15 10:18 UTC by ivantjh

Add rapidjson library for json support. Now pulls paddle 1 and 2 controls from json file. This allows modification of controls within the game if the feature is needed.

2017-01-15 10:59 UTC, chesterhow requested changes

2017-01-15 10:59 UTC, chesterhow commented on src/graphics.h
> +#ifdef _DEBUG
r u srs

2017-01-15 11:04 UTC, chesterhow requested changes

2017-01-15 11:04 UTC, chesterhow commented on src/paddle.cpp
> +	}
When moving up you set to -= velocity. But when moving down you set yvelocity = velocity. What are you trying to do here?

Are you trying to set the velocity to negative? `yVelocity = -paddleNS::VELOCITY`
Or did you forget to add a plus? `yVelocity += paddleNS::VELOCITY`

2017-01-15 11:04 UTC, chesterhow commented on src/graphics.h
> +	{
Please standardize the braces

2017-01-15 11:12 UTC, chesterhow commented on src/paddle.cpp
> +	}
I'm assuming the first option. Because the 2nd one would mean the paddle has acceleration, which probably shouldnt be the case

2017-01-15 11:44 UTC, ivantjh commented on src/graphics.h
> +#ifdef _DEBUG
oops

2017-01-15 11:46 UTC, ivantjh commented on src/paddle.cpp
> +	}
Ya, its the first option. I will shift the negative sign to the back

2017-01-16 05:00 UTC, chesterhow approved these changes

2017-01-16 05:00 UTC, merged