Paddle pickup collision
CIA-hideout/pongstar pull request #25
Opened 2017-02-02 06:33 UTC by JeromeTiong

@chesterhow @ivantjh

2017-02-02 10:25 UTC, chesterhow requested changes

2017-02-02 10:25 UTC, chesterhow commented on src/pickup.cpp
> +			}
Can you combine them? The only thing that's different is the target type

```c++
messageNS::TARGET_TYPE targetType = (ent.get() > GAME_WIDTH / 2) ? messageNS::RIGHT_P : messageNS::LEFT_P;
```

This line should suffice. Then you init your message with `targetType`

2017-02-03 15:13 UTC, JeromeTiong commented
@chesterhow

2017-02-03 15:18 UTC, chesterhow approved these changes

2017-02-03 15:19 UTC, merged